import Image from 'next/image';
import Link from 'next/link';
import CTASection from '@/components/CTASection';
import PageHero from '@/components/PageHero';
import Section from '@/components/Section';
import { pageMetadata } from '@/lib/metadata';
import { companyHeroImages, heroImages } from '@/lib/hero-images';

export const metadata = pageMetadata('About UXUE', 'Learn about UXUE Company Ltd, a Kenya-based technology-first security and ICT integration company.', '/about', heroImages.infrastructure.src);

export default function AboutPage() {
  return <><PageHero title="Technology integration with an operational point of view." description="UXUE Company Ltd is a Kenya-based, technology-first security and ICT integration company helping organisations protect assets, connect systems and automate operations." images={companyHeroImages} breadcrumbs={[{ label: 'About' }]} />
    <Section className="section"><div className="detail-intro"><aside className="detail-intro__aside"><p>Security systems, enterprise networks, smart automation, cybersecurity and business technology—designed as parts of one operating environment.</p></aside><div><h2>Built to solve the whole infrastructure problem.</h2><p className="lede">UXUE focuses on modern technology implementation rather than traditional guarding services. The work connects protection, productivity and digital operations through systems that are practical to use and maintain.</p><p>The company serves organisations in Kenya and East Africa, bringing local operating context to enterprise infrastructure decisions.</p></div></div></Section>
    <section className="image-split"><div className="image-split__image"><Image src="/images/power.jpg" alt="Technology infrastructure equipment" fill sizes="(max-width: 767px) 100vw, 50vw" /></div><div className="image-split__content"><div><h2>Designed for African enterprise environments.</h2><p className="lede">Technology choices must account for the facility, power, connectivity, people and support realities of the environment where they will operate.</p><Link href="/blog/technology-infrastructure-african-enterprises" className="text-link">Read the perspective</Link></div></div></section>
    <Section className="section section--dark"><div className="section-heading"><div><h2>A clear mission. A long view.</h2></div></div><div className="feature-grid dark-grid"><article className="feature-card"><span>VISION</span><h3>To become Africa’s leading integrated security and technology solutions partner.</h3></article><article className="feature-card"><span>MISSION</span><h3>To deliver reliable, intelligent and modern technology solutions that enhance protection, productivity and digital transformation.</h3></article></div></Section>
    <Section className="section section--paper"><div className="section-heading"><div><h2>How UXUE approaches the relationship.</h2></div><p>Values from the existing company profile, expressed through the way projects are planned and delivered.</p></div><div className="feature-grid">{[['Integrity & professionalism', 'Transparent engagement and professional standards throughout delivery.'], ['Innovation & improvement', 'Continued attention to changing infrastructure needs and technical practice.'], ['Reliability & excellence', 'Systems designed to perform consistently in demanding environments.'], ['Customer-focused solutions', 'Architecture shaped around the organisation’s requirement and risk profile.']].map(([title, text], index) => <article className="feature-card" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></Section>
    <Section className="section"><div className="section-heading"><div><h2>Beyond supplying hardware.</h2></div></div><div className="number-list">{['End-to-end technology integration', 'Experienced technical delivery', 'Structured deployment and support', 'Modern, future-aware system design', 'A partner for businesses and institutions'].map((item, index) => <div key={item}><span className="number-list__index">0{index + 1}</span><h3>{item}</h3></div>)}</div></Section><CTASection /></>;
}
